### ISSUE TITLE
Default CSS style

### ISSUE THREAD

**Issue by XtoManuel** [DailyBotHQ/universal-emoji-parser#221]
To correctly adjust the size of the emojis within the element where they are located, I had to globally define the following style:
```css
img.emoji {
     height: 1em;
     width: 1em;
     margin: 0 0.05em 0 0.1em;
     vertical-align: -0.1em;
}
```
